name: Build and Release Tauri App

on:
  push:
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          # - platform: "macos-latest"
          #   args: "--target x86_64-apple-darwin"
          #   arch: "amd64"
          # - platform: "macos-latest"
          #   args: "--target aarch64-apple-darwin"
          #   arch: "aarch64"
          # - platform: "ubuntu-22.04"
          #   args: ""
          #   arch: "amd64"
          # - platform: "windows-latest"
          #   args: ""
          #   arch: "amd64"
          - platform: "ubuntu-22.04"
            args: "--target aarch64-unknown-linux-gnu"
            arch: "aarch64"

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ubuntu AMD64)
        if: matrix.platform == 'ubuntu-22.04' && matrix.args == ''
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libclang-dev

      - name: Install dependencies (Ubuntu AArch64)
        if: matrix.platform == 'ubuntu-22.04' && matrix.args == '--target aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf \
            libclang-dev \
            crossbuild-essential-arm64 \
            pkg-config \
            libglib2.0-dev:arm64 \
            libgtk-3-dev:arm64 \
            libwebkit2gtk-4.1-dev:arm64 \
            libayatana-appindicator3-dev:arm64
          echo "PKG_CONFIG_SYSROOT_DIR=/usr/aarch64-linux-gnu" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || matrix.arch == 'aarch64' && 'aarch64-unknown-linux-gnu' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.14.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"

      - name: Install frontend dependencies
        run: pnpm install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__-${{ matrix.arch }}
          releaseName: "App v__VERSION__ (${{ matrix.arch }})"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
